server:
  port: 8081


spring:
  datasource:
    db1:
      jdbc-url: jdbc:postgresql://127.0.0.1:5432/workdb
      username: postgres
      password: 876606
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      driver-class-name: org.postgresql.Driver

    db2:
      jdbc-url: jdbc:postgresql://127.0.0.1:5432/workdb2
      username: postgres
      password: 876606
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      driver-class-name: org.postgresql.Driver

  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
  redis:
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
      port: 6379

mybatis:
  type-aliases-package: cn.connext.toolback.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl